--CREATE DATABASE Banco;
--USE Banco;
--USE master;
--ALTER DATABASE Banco MODIFY NAME = Agenda;
--USE Agenda;
--CREATE TABLE PESSOAL(
--	MATRICULA INTEGER,
--	NOME VARCHAR(50),
--	NASCIMENTO DATE,
--	SEXO CHAR(1),
--	SALARIO MONEY,
--	);

--ALTER TABLE PESSOAL ADD OBSERVACAO VARCHAR(200);
--ALTER TABLE PESSOAL ALTER COLUMN OBSERVACAO VARCHAR(150);
--ALTER TABLE PESSOAL DROP COLUMN OBSERVACAO;

--SELECT * FROM PESSOAL;
